stages:
  - build

build_windows:
  image: cdrx/pyinstaller-windows:python3
  stage: build
  script:
    - pip install -r requirements.txt
    - pyinstaller --noconsole --onefile src/main/python/main.py
  artifacts:
    paths:
      - dist/main.exe
    expire_in: 1 week

build_mac:
  image: python:3.10  # macOS runners are not available on GitLab, so we use Linux and macOS cross-compilation
  stage: build
  before_script:
    - pip install pyinstaller
  script:
    - pyinstaller --noconsole --onefile --windowed --name="ThymosControl" src/main/python/main.py
  artifacts:
    paths:
      - dist/ThymosControl
    expire_in: 1 week