stages:
  - build
  - release

variables:
  APP_NAME: "ThymosLoader"

build_windows:
  stage: build
  tags:
    - windows
  script:
    - python -m venv venv
    - source venv/Scripts/activate
    - pip install fbs PyQt5
    - fbs clean
    - fbs freeze
  artifacts:
    paths:
      - "target"

build_mac:
  stage: build
  tags:
    - macos
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install fbs PyQt5
    - fbs clean
    - fbs freeze
  artifacts:
    paths:
      - "target"

build_linux:
  stage: build
  tags:
    - linux
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install fbs PyQt5
    - fbs clean
    - fbs freeze
  artifacts:
    paths:
      - "target"

release:
  stage: release
  script:
    - echo "Releasing application..."
  dependencies:
    - build_windows
    - build_mac
    - build_linux
  artifacts:
    paths:
      - "target"