serial:
  port: /dev/cu.Bluetooth-Incoming-Port
machine setup:
  loadcell1:
    enable: false
  loadcell2:
    enable: true
  loadcell3:
    enable: false
experiment setup:
  folder: /Users/onpis/Documents/ExperimentalniCentrum/Zatezovak/TestMeasurements
  parameters:
    distance: 20.0
    force drop: 5.0
    force drop percent: 30.0
    photos:
      enable: true
      frequency: 1.0
    safe force: 5000.0
    speed: 1.0
  description:
    author: Ondrej
    title: test
