serial:
  port: /dev/cu.usbmodem1301
machine setup:
  loadcell1:
    enable: false
  loadcell2:
    enable: true
  loadcell3:
    enable: false
  acquisition interval: 0.05
experiment setup:
  folder: /Users/onpis/Documents/ExperimentalniCentrum/Zatezovak/TestMeasurements
  parameters:
    distance: 20.0
    force drop:
      enable: true
      limit: 5.0
      percent: 30.0
    photos:
      enable: true
      frequency: 1.0
    safe force: 50.0
    speed: 1.0
  description:
    author: Ondrej
    title: test
    description: desc
